services:
  # The name of the service must match the full namespace class
  ImageBullet\Controller\ImageBulletController:
    class: ImageBullet\Controller\ImageBulletController
    arguments:
      - '@doctrine.cache.provider'